---
# tasks file for test1

- name: installing epel-release
  yum:
    name: epel-release
    update_cache: yes
    state: latest
- name: installing nginx
  package:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: restarted
