---
# tasks file for nginx_docker
- name: deploy nginx docker
  shell: systemctl is-active docker
  register: docker_status
  changed_when: false
  failed-when: docker_status.stdout != "active"

- name: pull nginx image in docker
  docker_image:
    name: nginx
    source: pull
  
- name: run nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - 80:80